plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

dependencies {
    api 'com.google.code.gson:gson:2.10.1'
    compileOnly 'org.slf4j:slf4j-api:2.0.9'
}
